BaseURL = "https://fanlychie.github.io/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "Fanlychie Blog"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true

[Author]
  Name = "范忠云"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[Params]
  AuthorHomepage = "https://fanlychie.github.io/"
  BottomIntroduce = "I do not know where to go <br> but I have been on the road"
  Description = ""
  Subtitle = "昔风不起，唯有努力生存"
  #Weibo = "coderzh"
  #WeiboID = 1816308191
  #Twitter = "coderzh"
  GitHub = "fanlychie"
  #Facebook = "coderzh"
  #LinkIn = "coderzh"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006-01-02"
  MonthFormat = "2006-01"
  FancyBox = true

  [Params.GoogleAnalytics]
    ID = "UA-10147768-2"

  [Params.Disqus]
    ShortName = "fanlychie"

  [Params.Strings]
    Search = "搜索一下"
    PageNotFound = "你访问的页面走丢了"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2